version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install packages
          command: |
            python3 -m venv venv
            . venv/bin/activate
            # pip install -r requirements/dev.txt
            make install
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - 'venv'
      - run:
          name: lint the files
          command: |
              . venv/bin/activate
              make lint